spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: HERE_CLIENT_ID
            client-secret: HERE_CLIENT_SECRET
            token-uri: https://www.googleapis.com/oauth2/v4/token
            auth-uri: https://accounts.google.com/o/oauth2/auth
            redirect-uri: http://here-insert-client-redirect-uri
            resource-uri: https://www.googleapis.com/oauth2/v3/userinfo
            scope:
              - email
              - profile

jwt:
  secret: abcdefghijklmnopqrstuvwxyz1234567890abcdefghijklmn